<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <ProjectReference Include="..\..\MainCli\MainCli.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="data\**\*.*" CopyToOutputDirectory="Always" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Spectre.Console.Testing" Version="0.57.2" />
    </ItemGroup>
</Project>
