<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <ProjectReference Include="..\..\Core\FindJobHelper.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\MainCli\data\cv_template_config.tex"
              Link="data\cv_template_config.tex"
              CopyToOutputDirectory="Always" />
    </ItemGroup>
</Project>
