<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <ProjectReference Include="..\..\src\FindJobHelper.Cli\FindJobHelper.Cli.csproj" />
        <ProjectReference Include="..\ProviderFixtures\SyntheticProvider\SyntheticProvider.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="data\**\*.*" CopyToOutputDirectory="Always" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Spectre.Console.Testing" Version="0.57.2" />
    </ItemGroup>
</Project>
