<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IncludeUserSecrets>true</IncludeUserSecrets>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Core\FindJobHelper.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="OpenAI" Version="2.2.0" />
    </ItemGroup>
</Project>
