<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Anton.FindJobHelper.Templates</PackageId>
    <Description>Fictional starter Workspace for FindJobHelper.</Description>
    <PackageType>Template</PackageType>
    <IsPackable>true</IsPackable>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <ContentTargetFolders>content</ContentTargetFolders>
    <NoDefaultExcludes>true</NoDefaultExcludes>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="content\**\*" Pack="true" PackagePath="content" />
    <Content Include="..\..\scripts\setup-latex.sh" Pack="true" PackagePath="content\scripts\setup-latex.sh" Link="content\scripts\setup-latex.sh" />
    <Compile Remove="content\**\*.cs" />
    <None Include="..\..\LICENSE" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
